<?php
// $Id$

/**
 * @file
 * PHPMailer installation functions.
 */

/**
 * Implementation of hook_uninstall().
 */
function phpmailer_uninstall() {
  variable_del('smtp_on');
  variable_del('smtp_host');
  variable_del('smtp_hostbackup');
  variable_del('smtp_port');
  variable_del('smtp_protocol');
  variable_del('smtp_fromname');
  variable_del('smtp_username');
  variable_del('smtp_password');
  variable_del('smtp_keepalive');
  variable_del('smtp_debug');
}

