<?php
// $Id$

/**
 * @file
 * This module integrates PHPMailer with Drupal, both as native drupal_mail()
 * wrapper, and as part of the Mime Mail module.
 */

/**
 * Implementation of hook_perm().
 */
function phpmailer_perm() {
  return array('administer phpmailer settings');
}

/**
 * Implementation of hook_menu().
 */
function phpmailer_menu() {
  $items['admin/settings/phpmailer'] = array(
    'title' => 'Mail',
    'description' => 'Configure PHPMailer settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('phpmailer_settings_form'),
    'access callback' => 'phpmailer_settings_access',
    'file' => 'phpmailer.admin.inc',
  );
  return $items;
}

if (strpos(variable_get('smtp_library', ''), 'phpmailer') && !function_exists('drupal_mail_wrapper')) {
  /**
   * Implementation of drupal_mail_wrapper().
   */
  function drupal_mail_wrapper($message) {
    module_load_include('inc', 'phpmailer', 'includes/phpmailer.drupal');
    return phpmailer_send($message);
  }
}

/**
 * Implementation of hook_mailengine().
 */
function phpmailer_mailengine($op, $message = array()) {
  switch ($op) {
    case 'name':
      return t('PHPMailer');

    case 'description':
      return t('Mailing engine using the PHPMailer library.');

    case 'settings':
      module_load_include('inc', 'phpmailer', 'phpmailer.admin');
      return phpmailer_settings_form();

    case 'multiple':
    case 'single':
    case 'send':
      module_load_include('inc', 'phpmailer', 'includes/phpmailer.mimemail');
      return mimemail_phpmailer_send($message);
  }
}

/**
 * Extract address and optional display name of an e-mail address.
 *
 * @param $address
 *   A string containing one or more valid e-mail address(es) separated with
 *   commas.
 *
 * @return
 *   An array containing all found e-mail addresses split into mail and name.
 *
 * @see http://tools.ietf.org/html/rfc5322#section-3.4
 */
function phpmailer_parse_address($address) {
  $parsed = array();
  $regexp = "/^(.*) <([a-z0-9]+(?:[_\\.-][a-z0-9]+)*@(?:[a-z0-9]+(?:[\.-][a-z0-9]+)*)+\\.[a-z]{2,})>$/i";

  // Split multiple addresses and process each.
  foreach (explode(',', $address) as $email) {
    $email = trim($email);
    if (preg_match($regexp, $email, $matches)) {
      $parsed[] = array('mail' => $matches[2], 'name' => trim($matches[1], '"'));
    }
    else {
      $parsed[] = array('mail' => $email, 'name' => '');
    }
  }
  return $parsed;
}

/**
 * Block access to settings page if Mime Mail module is enabled.
 */
function phpmailer_settings_access() {
  // @todo Ony when global MM support is enabled?
  if (!module_exists('mimemail')) {
    return user_access('administer phpmailer settings');
  }
  return FALSE;
}

